#!/usr/bin/env bash
set -euo pipefail
PROJECT_ID="doxs2-e3d72"
REGION="us-central1"
SERVICE="doxs-api"

gcloud config set project "$PROJECT_ID"
gcloud services enable run.googleapis.com cloudbuild.googleapis.com artifactregistry.googleapis.com secretmanager.googleapis.com

gcloud run deploy "$SERVICE" \
  --source . \
  --region "$REGION" \
  --allow-unauthenticated \
  --port 8080 \
  --min-instances 1 \
  --max-instances 5 \
  --memory 512Mi \
  --cpu 1 \
  --set-secrets AUTH_MODE=AUTH_MODE:latest,DEV_LOGIN_MOCK=DEV_LOGIN_MOCK:latest,MYSQL_INSECURE_AUTH=MYSQL_INSECURE_AUTH:latest,SESSION_SECRET=SESSION_SECRET:latest,IDOXS_CLIENT_OXFORD_MYSQL_HOST=IDOXS_CLIENT_OXFORD_MYSQL_HOST:latest,IDOXS_CLIENT_OXFORD_MYSQL_PORT=IDOXS_CLIENT_OXFORD_MYSQL_PORT:latest,IDOXS_CLIENT_OXFORD_MYSQL_USER=IDOXS_CLIENT_OXFORD_MYSQL_USER:latest,IDOXS_CLIENT_OXFORD_MYSQL_PASSWORD=IDOXS_CLIENT_OXFORD_MYSQL_PASSWORD:latest,IDOXS_CLIENT_OXFORD_MYSQL_DATABASE=IDOXS_CLIENT_OXFORD_MYSQL_DATABASE:latest,IDOXS_CLIENT_WERT_MYSQL_HOST=IDOXS_CLIENT_WERT_MYSQL_HOST:latest,IDOXS_CLIENT_WERT_MYSQL_PORT=IDOXS_CLIENT_WERT_MYSQL_PORT:latest,IDOXS_CLIENT_WERT_MYSQL_USER=IDOXS_CLIENT_WERT_MYSQL_USER:latest,IDOXS_CLIENT_WERT_MYSQL_PASSWORD=IDOXS_CLIENT_WERT_MYSQL_PASSWORD:latest,IDOXS_CLIENT_WERT_MYSQL_DATABASE=IDOXS_CLIENT_WERT_MYSQL_DATABASE:latest,IDOXS_CLIENT_IVACORP_MYSQL_HOST=IDOXS_CLIENT_IVACORP_MYSQL_HOST:latest,IDOXS_CLIENT_IVACORP_MYSQL_PORT=IDOXS_CLIENT_IVACORP_MYSQL_PORT:latest,IDOXS_CLIENT_IVACORP_MYSQL_USER=IDOXS_CLIENT_IVACORP_MYSQL_USER:latest,IDOXS_CLIENT_IVACORP_MYSQL_PASSWORD=IDOXS_CLIENT_IVACORP_MYSQL_PASSWORD:latest,IDOXS_CLIENT_IVACORP_MYSQL_DATABASE=IDOXS_CLIENT_IVACORP_MYSQL_DATABASE:latest

SERVICE_URL="$(gcloud run services describe "$SERVICE" --region "$REGION" --format 'value(status.url)')"
echo "SERVICE_URL=$SERVICE_URL"
echo "Testing health..."
curl -i "$SERVICE_URL/api/health"
echo
